<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props" />
  <PropertyGroup>
    <AssemblyTitle>Akka.Remote</AssemblyTitle>
    <Description>Remote actor support for Akka.NET</Description>
    <TargetFrameworks>netstandard2.0;netstandard2.1;netcoreapp3.1</TargetFrameworks>
    <PackageTags>$(AkkaPackageTags);network</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
    <PropertyGroup>
        <Description>Remoting support for Akka.NET. Allows actors to communicate over the network.</Description>
        <TargetFrameworks>$(NetStandardLibVersion);$(NetLibVersion)</TargetFrameworks>
        <PackageTags>$(AkkaPackageTags);network</PackageTags>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>
    <ItemGroup>
        <EmbeddedResource Include="Configuration\Remote.conf" />
        <ProjectReference Include="..\Akka\Akka.csproj" />
      <ProjectReference Include="..\Akka.Streams\Akka.Streams.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="DotNetty.Handlers" Version="0.7.6" />
        <PackageReference Include="Google.Protobuf" Version="$(ProtobufVersion)" />
        <PackageReference Include="Grpc.Tools" Version="$(GrpcToolsVersion)">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

  <ItemGroup>
    <Protobuf Access="internal" Include="../../protobuf/ContainerFormats.proto" />
    <Protobuf Access="internal" Include="../../protobuf/SystemMessageFormats.proto" />
    <Protobuf Access="internal" Include="../../protobuf/WireFormats.proto" />

  </ItemGroup>
    <PropertyGroup>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    </PropertyGroup>
</Project>
